### ISSUE TITLE
2 controllers

### ISSUE THREAD

**Issue by MungoBerry** [emoose/Xb2XInput#11]
Hi,

I'm trying to use 2 original xbox controllers under Win10 x64 but only one is detected...
Any hint ?

Thank you.

**Comment by sebsjara** [comment]
yes please add support for four controls like xinput does. I have four controls with VID: 0xFFFF PID: 0xFFFF and when I connect the four or two or three it always recognizes only one

**Comment by sebsjara** [comment]
Ok, Its work, I uninstal then install again and now recognize all off them.
