### ISSUE TITLE
Mad Catz controller PID 0x4520 mis-named

### ISSUE THREAD

**Issue by rs1n** [emoose/Xb2XInput#18]
The current release (1.3.2) has the wrong name for Mad Catz PID 0x4520. This is the "MC2 Racing Wheel and Pedals" and not the "Control Pad Pro." Drivers work fine, but the device name is a bit misleading.

**Comment by Squall-Leonhart** [comment]
4520 is the Pro controller, and 4530 is the MC2 Racing wheel.

if there is also a MC2 racing wheel with the 4520 PID, Madcatz has stuffed up during a production run.
