### ISSUE TITLE
ScpVBus driver doesn't have valid signature on newer Win10 versions

### ISSUE THREAD

**Issue by emoose** [emoose/Xb2XInput#5]
EDIT: looks like ScpToolkit was superseded by ViGEm: https://github.com/ViGEm/ViGEmBus. Seems the driver for that works with Win10 perfectly fine, I'll have to look into getting XB2X migrated to it.

Great... I made this so that unsigned drivers _wouldn't_ be needed, but it turns out MS messed around with how driver signing works in newer Win10 versions, making the signature on ScpVBus.inf invalid, meaning you'd still need to allow unsigned drivers to use it ;_;

https://github.com/nefarius/ScpToolkit/issues/266 talks about it, but looks like the SCP dev has stopped working on it now though, so it's unlikely that'll have a fixed version released for it...

**Comment by boristh3blade** [comment]
Faced with same issue. I Use win 11 23H2. Accidentaly ps3 navi stop works. I try reinstall latest one SCP toolkits ( versions v1.7.277.16103-BETA and v1.7.276.16101-BETA) and faced with ScpVBus error. After that i removed it and install prev v1.6.238.16010 from my archive which was installed before. That fix my issue. That driver has older cert also expired but no errors with starting service.
