### ISSUE TITLE
Vigembus prereqs not installed or mentioned

### ISSUE THREAD

**Issue by suggestor** [emoose/Xb2XInput#6]
While the install script takes care of installing Vigembus, it does not install or mention the need for Vigembus's own prerequisites. So I ran into two issues (which are both documented on Vigembus Wiki, but not in the Xb2XInput readme).

Issue #1 - Microsoft KB3033929 update. This is necessary on Windows 7 to enable SHA-2 driver signing which is what Vigembus uses. Otherwise the driver will not load without disabling signing, which sort of defeats the purpose.

Issue #2 - Vigembus emulates the 360 controller through the actual controller driver, which therefore must be installed. Otherwise, when attempting to activate Xb2XInput it locks up the entire system.

Once these 2 items were addressed, I was able to use the program successfully.

**Comment by emoose** [comment]
Ah sorry about that, never really ran into those issues since I'm on Win10, but I'll add a link to the Vigembus wiki page to future readmes & the releases page.

To clarify, the driver you mention in the last issue is the 360 controller driver itself or the Vigembus driver?

**Comment by suggestor** [comment]
In the second issue I am referring to the Xbox 360 controller driver obtainable from Microsoft. The one you would ordinarily use for an actual 360 gamepad. Thanks for the response and for the program!
